version: '3.5'

services:

  server:
    image: challenge1_image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000
    depends_on:
      - db

  db:
    image: challenge1_db_image
    build:
      context: .
      dockerfile: Dockerfile-sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres